Import Libraries and Dataset

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
from pandas import read_csv
train_path=('/content/drive/MyDrive/Colab Notebooks/competition/train.csv')
test_path=('/content/drive/MyDrive/Colab Notebooks/competition/test.csv')
train=read_csv(train_path)
test=read_csv(test_path)
print(train.head(4))

  PassengerId HomePlanet CryoSleep  Cabin  Destination   Age    VIP  \
0     0001_01     Europa     False  B/0/P  TRAPPIST-1e  39.0  False
1     0002_01      Earth     False  F/0/S  TRAPPIST-1e  24.0  False
2     0003_01     Europa     False  A/0/S  TRAPPIST-1e  58.0   True
3     0003_02     Europa     False  A/0/S  TRAPPIST-1e  33.0  False

   RoomService  FoodCourt  ShoppingMall     Spa  VRDeck             Name  \
0          0.0        0.0           0.0     0.0     0.0  Maham Ofracculy
1        109.0        9.0          25.0   549.0    44.0     Juanna Vines
2         43.0     3576.0           0.0  6715.0    49.0    Altark Susent
3          0.0     1283.0         371.0  3329.0   193.0     Solam Susent

   Transported
0        False
1         True
2        False
3        False

Drop Values

In [ ]:
train.drop(['PassengerId','Name'],axis=1,inplace=True)

Null Values

In [ ]:
train.isna().sum()

HomePlanet      201
CryoSleep       217
Cabin           199
Destination     182
Age             179
VIP             203
RoomService     181
FoodCourt       183
ShoppingMall    208
Spa             183
VRDeck          188
Transported       0
dtype: int64

Info

In [ ]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   HomePlanet    8492 non-null   object
 1   CryoSleep     8476 non-null   object
 2   Cabin         8494 non-null   object
 3   Destination   8511 non-null   object
 4   Age           8514 non-null   float64
 5   VIP           8490 non-null   object
 6   RoomService   8512 non-null   float64
 7   FoodCourt     8510 non-null   float64
 8   ShoppingMall  8485 non-null   float64
 9   Spa           8510 non-null   float64
 10  VRDeck        8505 non-null   float64
 11  Transported   8693 non-null   bool
dtypes: bool(1), float64(6), object(5)
memory usage: 755.7+ KB

DataFrame

In [ ]:
df=pd.DataFrame(train)

Drop Null Values

In [ ]:
df=df.dropna()

In [ ]:
df.isna().sum()

HomePlanet      0
CryoSleep       0
Cabin           0
Destination     0
Age             0
VIP             0
RoomService     0
FoodCourt       0
ShoppingMall    0
Spa             0
VRDeck          0
Transported     0
dtype: int64

Cabin Column Splitting

In [ ]:
df[['Deck','Num','Side']]=df['Cabin'].str.split('/',expand=True)
df.drop(['Cabin'],axis=1,inplace=True)

Int to text

In [ ]:
df['CryoSleep']=df["CryoSleep"].astype(int)
df['VIP']=df["VIP"].astype(int)
df['Side']=df['Side'].map({'P':1,'S':2}).astype('int8')
df['Deck']=df['Deck'].map({'B':1, 'F':2, 'A':3, 'G':4, 'E':5, 'D':6, 'C':7, 'T':8}).astype('int8')
df['Destination']=df['Destination'].map({'TRAPPIST-1e':1, 'PSO J318.5-22':2, '55 Cancri e':3}).astype('int8')
df['HomePlanet']=df['HomePlanet'].map({'Europa':1,'Earth':2,'Mars':3}).astype('int8')

In [ ]:
df['Transported']=df['Transported'].unique

In [ ]:
print(df)

      HomePlanet  CryoSleep  Destination   Age  VIP  RoomService  FoodCourt  \
0              1          0            1  39.0    0          0.0        0.0
1              2          0            1  24.0    0        109.0        9.0
2              1          0            1  58.0    1         43.0     3576.0
3              1          0            1  33.0    0          0.0     1283.0
4              2          0            1  16.0    0        303.0       70.0
...          ...        ...          ...   ...  ...          ...        ...
8688           1          0            3  41.0    1          0.0     6819.0
8689           2          1            2  18.0    0          0.0        0.0
8690           2          0            1  26.0    0          0.0        0.0
8691           1          0            3  32.0    0          0.0     1049.0
8692           1          0            1  44.0    0        126.0     4688.0

      ShoppingMall     Spa  VRDeck  Transported  Deck   Num  Side
0              0.0     0.0     0.0            0     1     0     1
1             25.0   549.0    44.0            1     2     0     2
2              0.0  6715.0    49.0            0     3     0     2
3            371.0  3329.0   193.0            0     3     0     2
4            151.0   565.0     2.0            1     2     1     2
...            ...     ...     ...          ...   ...   ...   ...
8688           0.0  1643.0    74.0            0     3    98     1
8689           0.0     0.0     0.0            0     4  1499     2
8690        1872.0     1.0     0.0            1     4  1500     2
8691           0.0   353.0  3235.0            0     5   608     2
8692           0.0     0.0    12.0            1     5   608     2

[6764 rows x 14 columns]

In [ ]:
x=df[['HomePlanet','CryoSleep','Destination','Age','VIP','RoomService','FoodCourt','ShoppingMall','Spa','VRDeck','Deck','Num','Side']]
y=df['Transported']

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6764 entries, 0 to 8692
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   HomePlanet    6764 non-null   int8
 1   CryoSleep     6764 non-null   int64
 2   Destination   6764 non-null   int8
 3   Age           6764 non-null   float64
 4   VIP           6764 non-null   int64
 5   RoomService   6764 non-null   float64
 6   FoodCourt     6764 non-null   float64
 7   ShoppingMall  6764 non-null   float64
 8   Spa           6764 non-null   float64
 9   VRDeck        6764 non-null   float64
 10  Transported   6764 non-null   int8
 11  Deck          6764 non-null   int8
 12  Num           6764 non-null   object
 13  Side          6764 non-null   int8
dtypes: float64(6), int64(2), int8(5), object(1)
memory usage: 561.5+ KB

**Decision Tree**

In [ ]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier()
pedict=dtc.fit(x, y)

**R Value**

In [ ]:
r_value=dtc.score(x,y)
print('r_square_value :',r_value*100)

r_square_value : 99.98521584861028

# **Test Data_Set**

In [ ]:
df_test=pd.DataFrame(test)

In [ ]:
df_test

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name
0,0013_01,Earth,True,G/3/S,TRAPPIST-1e,27.0,False,0.0,0.0,0.0,0.0,0.0,Nelly Carsoning
1,0018_01,Earth,False,F/4/S,TRAPPIST-1e,19.0,False,0.0,9.0,0.0,2823.0,0.0,Lerome Peckers
2,0019_01,Europa,True,C/0/S,55 Cancri e,31.0,False,0.0,0.0,0.0,0.0,0.0,Sabih Unhearfus
3,0021_01,Europa,False,C/1/S,TRAPPIST-1e,38.0,False,0.0,6652.0,0.0,181.0,585.0,Meratz Caltilter
4,0023_01,Earth,False,F/5/S,TRAPPIST-1e,20.0,False,10.0,0.0,635.0,0.0,0.0,Brence Harperez
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4272,9266_02,Earth,True,G/1496/S,TRAPPIST-1e,34.0,False,0.0,0.0,0.0,0.0,0.0,Jeron Peter
4273,9269_01,Earth,False,NaN,TRAPPIST-1e,42.0,False,0.0,847.0,17.0,10.0,144.0,Matty Scheron
4274,9271_01,Mars,True,D/296/P,55 Cancri e,NaN,False,0.0,0.0,0.0,0.0,0.0,Jayrin Pore
4275,9273_01,Europa,False,D/297/P,NaN,NaN,False,0.0,2680.0,0.0,0.0,523.0,Kitakan Conale
4276,9277_01,Earth,True,G/1498/S,PSO J318.5-22,43.0,False,0.0,0.0,0.0,0.0,0.0,Lilace Leonzaley

Data PreProceesing on Test Data Set

In [ ]:
df_test.drop(['PassengerId','Name'],axis=1,inplace=True)

In [ ]:
df_test=df_test.dropna()

In [ ]:
df_test[['Deck','Num','Side']]=df_test['Cabin'].str.split('/',expand=True)
df_test.drop(['Cabin'],axis=1,inplace=True)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:3641: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]
/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4913: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [ ]:
df_test['CryoSleep']=df_test["CryoSleep"].astype(int)
df_test['VIP']=df_test["VIP"].astype(int)
df_test['Side']=df_test['Side'].map({'P':1,'S':2}).astype('int8')
df_test['Deck']=df_test['Deck'].map({'B':1, 'F':2, 'A':3, 'G':4, 'E':5, 'D':6, 'C':7, 'T':8}).astype('int8')
df_test['Destination']=df_test['Destination'].map({'TRAPPIST-1e':1, 'PSO J318.5-22':2, '55 Cancri e':3}).astype('int8')
df_test['HomePlanet']=df_test['HomePlanet'].map({'Europa':1,'Earth':2,'Mars':3}).astype('int8')

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
x_test=df[['HomePlanet','CryoSleep','Destination','Age','VIP','RoomService','FoodCourt','ShoppingMall','Spa','VRDeck','Deck','Num','Side']]

Model Apllication on Test Data Set

In [ ]:
test_y_pred=pedict.predict(x_test)

In [ ]:
submission_train = pd.DataFrame(data=test_y_pred, columns=['Transported'])

Adding Passenger_ID Column

In [ ]:
submission_passenger = pd.DataFrame(data=test['PassengerId'], columns=['PassengerId'])

# **Submission**

In [ ]:
submission = submission_passenger.join(other=submission_train)

In [ ]:
submission.head()

  PassengerId  Transported
0     0013_01            0
1     0018_01            1
2     0019_01            0
3     0021_01            0
4     0023_01            1

In [ ]:
submission['Transported'] = submission['Transported'].astype('bool')

# **Submission to csv**

In [ ]:
submission.to_csv('submission.csv', index=False)